"""add couchdb changes table

Revision ID: 4906aa244b4e
Revises: ca4b6b5b0e5e
Create Date: 2025-09-20 00:44:24.930589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4906aa244b4e'
down_revision: Union[str, Sequence[str], None] = 'ca4b6b5b0e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couchdb_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_seq', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couchdb_changes')
    # ### end Alembic commands ###
