"""add chunking

Revision ID: a1cdba9d2ac1
Revises: 482613b2c335
Create Date: 2025-09-19 00:54:14.312167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cdba9d2ac1'
down_revision: Union[str, Sequence[str], None] = '482613b2c335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('document_id', sa.Text(), nullable=True))
    op.add_column('docs', sa.Column('chunk_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_docs_slug'), table_name='docs')
    op.create_index(op.f('ix_docs_slug'), 'docs', ['slug'], unique=False)
    op.create_index(op.f('ix_docs_document_id'), 'docs', ['document_id'], unique=False)
    op.create_unique_constraint(None, 'docs', ['chunk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docs', type_='unique')
    op.drop_index(op.f('ix_docs_document_id'), table_name='docs')
    op.drop_index(op.f('ix_docs_slug'), table_name='docs')
    op.create_index(op.f('ix_docs_slug'), 'docs', ['slug'], unique=True)
    op.drop_column('docs', 'chunk_id')
    op.drop_column('docs', 'document_id')
    # ### end Alembic commands ###
