"""add created_at in docs

Revision ID: ca4b6b5b0e5e
Revises: a1cdba9d2ac1
Create Date: 2025-09-19 23:11:05.863864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4b6b5b0e5e'
down_revision: Union[str, Sequence[str], None] = 'a1cdba9d2ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_docs_created_at'), 'docs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_created_at'), table_name='docs')
    op.drop_column('docs', 'created_at')
    # ### end Alembic commands ###
