name: Deploy TACOS app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: tediverse/cicd/.github/workflows/deploy-fastapi.yml@main
    with:
      service_name: tacos
      app_dir: /opt/tacos
      lxc_user: tacos
    secrets:
      LXC_HOST: ${{ secrets.LXC_HOST }}
      ENV_FILE: ${{ secrets.ENV_FILE }}
      GH_RUNNER_KEY: ${{ secrets.GH_RUNNER_KEY }}
